### ISSUE TITLE
Running with Proton (Linux)

### ISSUE THREAD

**Issue by IvanClementino** [grimdoomer/DeadRisingEx#4]
I'm trying to run it through Steam Proton and I've renamed the launcher to "DeadRising.exe" to make Steam think it's the game file. But, of course, the launcher fails to launch the game because of the name. Is there a way for me to point the launcher to a different .exe name?

**Comment by grimdoomer** [comment]
Currently this is not supported. You can try to do the following to add the launcher exe as a non-steam game and see if that works: https://www.reddit.com/r/linux_gaming/comments/be4e46/how_to_play_nonsteam_games_through_proton_this/

**Comment by IvanClementino** [comment]
> Currently this is not supported. You can try to do the following to add the launcher exe as a non-steam game and see if that works: https://www.reddit.com/r/linux_gaming/comments/be4e46/how_to_play_nonsteam_games_through_proton_this/

It did work, thanks a lot for the suggestion!

If anyone wanna try, after adding the exe, go to properties and re-add it. Also remove the launch options. Steam added the paths wrongly initially.

Working config:
![image](https://user-images.githubusercontent.com/71457970/128246210-3c1ef0a3-b4f4-48df-a026-c86377643bee.png)

**Comment by IvanClementino** [comment]
It worked when I tried with the version available [here](https://deadrising2mods.proboards.com/thread/3104/deadrisingex-drex-unofficial-game-update). After updating to the latest version, the game closes right after opening, sadly.
```
ImGuiRenderer::Initialize(): failed to compile vertex shader 0x80004005
ERROR: Failed to initialize ImGuiRenderer!
```

Edit:
Version v1.5.7.45 (before the implementation of the in-game console) works!

**Comment by grimdoomer** [comment]
I suspect this is because it either cant find d3dcompiler_47.dll or it fails when trying to compile the shaders. You could try finding d3dcompiler_47.dll from the directx redistributable (http://www.microsoft.com/en-us/download/confirmation.aspx?id=35) and placing it in the game directory and see if that resolves the issue.

**Comment by IvanClementino** [comment]
> I suspect this is because it either cant find d3dcompiler_47.dll or it fails when trying to compile the shaders. You could try finding d3dcompiler_47.dll from the directx redistributable (http://www.microsoft.com/en-us/download/confirmation.aspx?id=35) and placing it in the game directory and see if that resolves the issue.

Used protontricks to install d3dcompiler_47.dll and it worked!! 
Thank you for the help.

**Comment by awsms** [comment]
I can't see deadrisingex_test.arc, or any mod really in the mod manager.
@IvanClementino your mods are located in `SteamLibrary/steamapps/common/Dead Rising/nativeWin64/Mods` ?
