### ISSUE TITLE
Is there any way to make the DREX launcher point to an executable with a different name?

### ISSUE THREAD

**Issue by eggmanstudio** [grimdoomer/DeadRisingEx#5]
So here's the deal. I would like to be able to launch DREX through Steam, _without_ needing to add the launcher as a non-Steam game. The only way I have found to do this is to use a program called SteamEdit, which makes changes to Steam's appinfo.vdf file. The issue is, the file resets itself after a while, meaning I have to keep doing it.

This leads me to my question. If I could somehow rename the game's executable and make it so the DREX launcher points to that instead, I wouldn't have to use SteamEdit because I could simply rename DeadRisingLauncher to "DeadRising.exe" - allowing it to be launched through Steam normally.

**Comment by grimdoomer** [comment]
Is there a reason you don't want to add it as a non-steam game?

**Comment by eggmanstudio** [comment]
> Is there a reason you don't want to add it as a non-steam game?

Purely personal taste. I don't like having multiple entries for the same game in my Steam library, it's a little too rough and ready for my tastes

**Comment by grimdoomer** [comment]
Closing this as won't fix as the issue doesn't really pertain to DREX as much as it does user environment customizations.

**Comment by cammysorammy** [comment]
not to necro an old issue, but if you want something like this, you could put DREX into your game folder and put this into your launch options:

"E:\SteamLibrary\steamapps\common\Dead Rising\DeadRisingLauncher.exe" %command%

obviously replace the game path with yours and it'll launch like normal. figured i'd mention it anyway for anyone interested.
