### ISSUE TITLE
Fixing port inconsistancies

### ISSUE THREAD

**Issue by Patrxgt** [grimdoomer/DeadRisingEx#8]
The PC remaster of the game has some inconsistencies, that affect gameplay and add graphical issues.
[YT comparison](https://youtu.be/gqNYQEsYOi0?t=58)

The ones, that can be considered as "serious" issues are:
1. Camera zoom-in faster than in the X360 release.
2. Audio sounds lower quality than the X360 version.
3. Most of the in-game music fail to loop seamlessly (like in the X360 version).
4. Lawn mower sound doesn't loop properly, when "mowing" zombies (like in the X360 version).
5. In "Overtime Mode" every character is black (lacks textures) (occurs only in Leisure Park).

The ones, that can be considered as "less problematic" inconsistencies are:
1. In the shop "In the Closet" you can put on a T-shirt that shows a topless woman in the X360 version. It's censored in remastered releases.
2. A painting that can be found in the "Casual Gals" shop that shows the same girl has been censored with a white shirt in the remastered releases.

**Comment by grimdoomer** [comment]
Closing this as won't fix. The goal of DREX is to provide a framework for developing code changes to the game, add further modding support, and to fix critical, game breaking bugs that would cause the game to crash or prohibit you from playing normally. These types of bugs do not meet the bar for something that DREX would aim to fix as they do not cause the game to crash or prohibit normal game play.
